name: CI-CD_grupo5

on:
  push:
    branches:
      - grupo#5
  pull_request:
    branches:
      - grupo#5

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del c贸digo
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Construcci贸n del proyecto
        run: mvn clean package

      - name: Ejecutar pruebas
        run: mvn test

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout del c贸digo
        uses: actions/checkout@v3

      - name: Iniciar sesi贸n en DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir y subir imagen Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/app:latest
