name: ci-cd_grupo#5
on:
  pull_request:
    branches:
      - develop
      - grupo#5
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Construcción del proyecto
        run: mvn clean package

      - name: Subir artefacto
        uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: target/*.jar
