name: CI-CD-Alternativo

on:
  push:
    branches:
      - grupo-1
  pull_request:
    branches:
      - grupo-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Ejecutar pruebas unitarias
        run: mvn test

      - name: Construcción del proyecto
        run: mvn clean package

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Construir y subir imagen Docker
        uses: docker/build-push-action@v4
        with:
          push: false
          tags: my-docker-repo/app:latest
