name: CI-CD + Trivy

on:
  pull_request:
    branches:
      - grupo6
  push:
    branches:
      - grupo6

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Construcción del proyecto
        run: mvn clean package

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar

  security_scan:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Ejecutar escaneo de seguridad con Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: 1
          ignore-unfixed: true
